language: node_js
sudo: required
node_js:
  - "stable"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe"
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo add-apt-repository "deb http://dl.google.com/linux/chrome/deb/ stable main"
  - sudo apt-get update
  - sudo apt-get install -y google-chrome-stable
  - export CHROME_BIN=/usr/bin/google-chrome
  - npm up -g npm
  - npm --version
  - npm i -g gulp karma

git:
  depth: 10
