language: node_js
node_js:
  - "stable"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip
  - export CHROME_BIN=$TRAVIS_BUILD_DIR/chrome-linux/chrome
  - npm up -g npm
  - npm --version
  - npm i -g gulp karma

git:
  depth: 10
